#!/bin/bash
# start-sshd --- Start (and connect to) ssh server.

docker run -p 22 -d mckoss/sshd
URI=$(docker port $(docker ps -l -q) 22)
IF=${URI/:*/}
PORT=${URI/*:/}

echo "Connecting to ${IF}:${PORT} as user service (password 'service'):"
sleep 1
ssh service@${IF} -p $PORT
